### PR TITLE
Response parser class implementation

### PR DESCRIPTION
**Pull request by MohitMaliFtechiz**
Please check and merge the latest code.

### CODE REVIEW

**Comment by sigrlami** [comment]
@MohitMaliFtechiz can you add just 2 sentences explanation to Readme about this generalized class and why it's useful for end user?

**Review by sigrlami — CHANGES_REQUESTED** [review]
Can you validate what's going on with tests? I can see multiple comments added on prints.

**Comment by MohitMaliFtechiz** [comment]
> Can you validate what's going on with tests? I can see multiple comments added on prints.

Do you want remove commented "print_r" statement.

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz can you add just 2 sentences explanation to Readme about this generalized class and why it's useful for end user?

Do you want add explanation of "Response parser class" in readme file ?

**Comment by sigrlami** [comment]
> > Can you validate what's going on with tests? I can see multiple comments added on prints.
> 
> Do you want remove commented "print_r" statement.

yes, It should be either cleaned up or unified in a function.

**Comment by sigrlami** [comment]
> > @MohitMaliFtechiz can you add just 2 sentences explanation to Readme about this generalized class and why it's useful for end user?
> 
> Do you want add explanation of "Response parser class" in readme file ?

Yes, a small explanation of how it works for future developers.

**Comment by MohitMaliFtechiz** [comment]
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

> > > Can you validate what's going on with tests? I can see multiple comments added on prints.
> > 
> > 
> > Do you want remove commented "print_r" statement.
> 
> yes, It should be either cleaned up or unified in a function.

ok i will update

**Pull request closed without merging**
